version: '3.6'

services:
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
      # - ./db:/var/lib/mysql
      # - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=teamformationassistant
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpwd
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    # networks:
    #   - application_network

  # mocker:
  #   build:
  #     context: ./mocker
  #   container_name: mocker
  #   command: ['npm', 'start']
  #   depends_on:
  #     - database
  #   networks:
  #     - application_network

  node_server:
    restart: always
    build:
      context: ./backend
    command: ['npm', 'start']
    # ports:
    #   - 8080:8080
    # networks:
    #   - application_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  # ml_server:
  #   build:
  #     context: ./ml-service
  #   container_name: ml_server
  #   command: ['flask', 'run', '--host=0.0.0.0']
  #   depends_on:
  #     - mocker
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - application_network

  
