version: '3.6'

services:
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=teamformationassistant
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpwd
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306

  node_server:
    restart: always
    build: .
    command: ['npm', 'start']
    environment:
      - PORT=8080
      - DB_TYPE=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbuserpwd
      - DB_DATABASE=teamformationassistant
    ports:
      - 8080:8080

